AttributeError: 'EndianBinaryReader_Memoryview_BigEndian' object has no attribute 'is_changed' (#185)
* Update environment.py

Fixed a bug where Enviroment.save() function was always assuming all asset objects have the "is_changed" attributes, causing it to raise an exception if it encountered an "EndianBinaryReader_Memoryview_BigEndian" object, as that object doesn't have an "is_changed" attribute.

* Fix indent and use getattribute

* env-save: Use fname and fitem

---------

Co-authored-by: Rudolf Kolbe <rkolbe96@gmail.com>